openapi: 3.0.0
info:
  title: student help
  version: '1.0'
  license:
    name: AGPL
  description: Student to student help providing API
  contact:
    name: Student Help API
    email: contact@ecam.be
servers:
  - url: 'https://api.ecam.be/student-help'
    description: Production
paths:
  '/messages/{messageId}':
    parameters:
      - $ref: '#/components/parameters/messageId'
    get:
      summary: Get Message Info by Message ID
      tags: []
      responses:
        '200':
          description: Message Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples: {}
        '404':
          $ref: '#/components/responses/Not-Found'
      operationId: get-messages-messageId
      description: Retrieve the information of the message with the matching message ID.
    patch:
      summary: Update Message Information
      operationId: patch-messages-messageId
      responses:
        '200':
          description: Message Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          $ref: '#/components/responses/Not-Found'
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                Content was empty:
                  value:
                    message: Content may not be empty
      description: Update the information of an existing message.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
        description: Patch message content to update.
    delete:
      summary: ''
      operationId: delete-messages-messageId
      responses:
        '204':
          description: Message was successfully deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
                x-examples:
                  example-1:
                    message: huskjndknlj
              examples:
                Not your message:
                  value:
                    message: 'This message does not belong to you, you cannot delete it'
      description: Delete an existing message
  /messages:
    post:
      summary: Create New Message
      operationId: post-messages
      responses:
        '200':
          description: Message Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Missing Required Information
        '404':
          $ref: '#/components/responses/Not-Found'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
        description: Post the necessary fields for the API to create a new message.
      description: Create a new message.
  /threads:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: Found threads
          content:
            application/json:
              schema:
                type: object
                properties:
                  threads:
                    type: array
                    items:
                      $ref: '#/components/schemas/Thread'
      operationId: get-threads
      description: Get a list of published threads
components:
  schemas:
    Message:
      description: A sent message
      type: object
      title: Message
      x-examples:
        An answer to a preexisting question:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          content: 'https://lmgtfy.app/?q=aop+inverseur+formule'
          upvotes: 0
          downvotes: 2
          datePosted: '2019-08-24T14:15:22Z'
          dateModified: '2019-08-24T14:15:22Z'
          authorId: ee6f7132-bd0a-4fcd-83b3-a8022377067b
          parent: 42e2bc1b-6741-4e2e-b138-97b4a342c999
          children:
            - 0cb5c5de-ce35-47a4-a1db-3ea542dfb9b8
            - d2a631d5-dbdc-4aca-9268-1592449de5bf
        A correction for another answer:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          content: |-
            Mais non, en python 3 il faut mettre des parenthèses pour les appels à `print`.

            Donc on fait `print("Hello, World!")` et  plus `print "Hello, World!"`
          upvotes: 3
          downvotes: 0
          datePosted: '2019-08-24T14:15:22Z'
          dateModified: '2019-08-24T14:15:22Z'
          authorId: ee6f7132-bd0a-4fcd-83b3-a8022377067b
          parent: 42e2bc1b-6741-4e2e-b138-97b4a342c999
          children: []
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        content:
          type: string
          minLength: 1
          description: 'The message content, in MarkDown'
        upvotes:
          type: number
          minimum: 0
          readOnly: true
        downvotes:
          type: number
          minimum: 0
          readOnly: true
        datePosted:
          type: string
          minLength: 1
          format: date-time
          readOnly: true
        dateModified:
          type: string
          minLength: 1
          format: date-time
          readOnly: true
        authorId:
          type: string
          minLength: 1
          format: uuid
          readOnly: true
        parent:
          type: string
          format: uuid
          description: The parent message or thread
          readOnly: true
        children:
          type: array
          uniqueItems: true
          description: |-
            The responses

            The children will have their `parent` field set to the `id` of this message
          items:
            type: string
            format: uuid
            readOnly: true
          readOnly: true
      required:
        - id
        - content
        - upvotes
        - downvotes
        - datePosted
        - dateModified
        - authorId
        - children
    Thread:
      title: Thread
      type: object
      description: ''
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
        message:
          $ref: '#/components/schemas/Message'
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
      required:
        - id
        - title
        - message
  securitySchemes:
    Global JWT:
      type: oauth2
      flows:
        implicit:
          scopes:
            student-help.post: Post messages
            student-help.rate: Vote on messages
            student-help.thread: Create new threads
          authorizationUrl: 'https://api.ecam.be/oauth2/authorize'
  parameters:
    messageId:
      schema:
        type: string
        format: uuid
      name: messageId
      in: path
      required: true
      description: Id of an existing message.
  responses:
    Not-Found:
      description: Requested object was not found in our database
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          examples:
            Message:
              message: Message not found
            Thread:
              message: Thread not found
security:
  - API Key - 1: []
